apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "football-lesson-generator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "football-lesson-generator.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            {{- include "football-lesson-generator.labels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ include "football-lesson-generator.serviceAccountName" . }}
          restartPolicy: OnFailure

          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          containers:
            - name: football-lesson-generator
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}

              command: ["/app/entrypoint.sh"]

              envFrom:
                - configMapRef:
                    name: {{ include "football-lesson-generator.fullname" . }}-config
                - secretRef:
                    name: {{ required "confluence.existingSecretName is required" .Values.confluence.existingSecretName }}

              volumeMounts:
                - name: google-sa
                  mountPath: {{ .Values.google.saMountPath }}
                  subPath: {{ .Values.google.saSecretKey }}
                  readOnly: true

              resources:
                {{- toYaml .Values.resources | nindent 16 }}

          volumes:
            - name: google-sa
              secret:
                secretName: {{ required "google.saSecretName is required" .Values.google.saSecretName }}
