apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "football-lesson-generator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "football-lesson-generator.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            {{- include "football-lesson-generator.labels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ include "football-lesson-generator.serviceAccountName" . }}
          restartPolicy: OnFailure
          containers:
            - name: football-lesson-generator
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - configMapRef:
                    name: {{ include "football-lesson-generator.fullname" . }}-config
                - secretRef:
                    name: {{ include "football-lesson-generator.fullname" . }}-confluence
              volumeMounts:
                - name: google-sa
                  mountPath: /secrets
                  readOnly: true
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          volumes:
            - name: google-sa
              secret:
                secretName: {{ .Values.google.saSecretName }}
          nodeSelector:
            {{- toYaml .Values.nodeSelector | nindent 12 }}
          tolerations:
            {{- toYaml .Values.tolerations | nindent 12 }}
          affinity:
            {{- toYaml .Values.affinity | nindent 12 }}
