apiVersion: v1
kind: Secret
metadata:
  name: {{ include "football-lesson-generator.fullname" . }}-confluence
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "football-lesson-generator.labels" . | nindent 4 }}
type: Opaque
stringData:
  CONF_USER: {{ .Values.confluence.user | quote }}
  CONF_PASS: {{ .Values.confluence.password | quote }}
